### PR TITLE
Use unique filename for wrapper script.

### PR DESCRIPTION
**Pull request by vext01**
Similar kind of thing for the wrapper script filename.

OK?

### CODE REVIEW

**Comment by ltratt** [comment]
This looks fine. However, we need to rebase it against master, before I can merge it.

**Comment by vext01** [comment]
Synced.

**Comment by ltratt** [comment]
That looks fine to me. You can squash now if you want.

**Comment by vext01** [comment]
Will just wait for tests.

**Comment by vext01** [comment]
Splat

**Pull request merged**
