### PR TITLE
Bogus line.

### PR DESCRIPTION
**Pull request by vext01**
This is an un-needed line. Maybe a fudged merge conflict? Blast it with fire.

### CODE REVIEW

**Comment by ltratt** [comment]
It's too big! Please break this PR up into one PR per character ;)

[More seriously, will wait for tests to run, then merge.]

**Comment by vext01** [comment]
Careful what you wish for doctor!

**Comment by ltratt** [comment]
Ah, this needs rebasing against master.

**Comment by vext01** [comment]
Sync.

**Pull request merged**
