### PR TITLE
Use syscalls

### PR DESCRIPTION
**Pull request by vext01**
Here is the initial Krun support for the custom kernel.

I need to fix the tests, but we can start reviewing.

Please don't merge yet.

### CODE REVIEW

**Comment by ltratt** [comment]
This looks good to me. With the change of pushing the `for` loop into the kernel have the ratios got tighter? [My intuition is that they should have... but I've been wrong before!]

**Comment by vext01** [comment]
They are still pretty tight, yeah. I'll give you a max/min once my run finishes.

**Comment by ltratt** [comment]
I think they should be *tighter* than before, since we've now removed more syscall overhead.

**Comment by vext01** [comment]
For my smaller run, which ran several hours, the max and min ratios we saw was:
(0.9982062780269059, 1.0008437801350047)

Pretty good going if you ask me.

**Comment by ltratt** [comment]
Absolutely! 

I think we're ready to squash both PRs and merge?

**Comment by vext01** [comment]
note that those are extremes.

Full log here:
http://theunixzoo.co.uk/random/amlog

**Comment by ltratt** [comment]
Don't worry, I knew what you meant.

**Comment by vext01** [comment]
I'd just like to plot what i collected so far to check the core-cycles.

**Comment by ltratt** [comment]
OK.

**Comment by vext01** [comment]
http://theunixzoo.co.uk/random/plots.pdf

Looks fine to me, but I'd like your opinion. Note these are only 200 iters long.

**Comment by vext01** [comment]
splat

**Pull request merged**
