### PR TITLE
Update JRubyTruffle VM def for the new version.

### PR DESCRIPTION
**Pull request by vext01**
Oops. Forgot to raise a PR for the new JRubyTruffle on the Krun side.

The way you invoke JRubyTruffle changed, hence these changes.

OK?

### CODE REVIEW

**Comment by ltratt** [comment]
This time we have failing tests.

**Comment by vext01** [comment]
fixed.

**Comment by ltratt** [comment]
OK, let's squash then I can merge.

**Comment by vext01** [comment]
splat.

**Comment by vext01** [comment]
Looks like travis are having network issues today...

**Pull request merged**
