### PR TITLE
Core cycles msr improvements

### PR DESCRIPTION
**Pull request by vext01**
Here are a couple of miscellaneous improvements to the work we merged yesterday.

See individual commit messages.

Thanks

### CODE REVIEW

**Comment by ltratt** [comment]
If `u_int64_t` is internal, should we also delete its definition?

**Comment by ltratt** [comment]
Otherwise, this looks good and ready for merge.

**Comment by vext01** [comment]
I think undefining `u_int64_t` would be asking for trouble. On some systems the system headers use them, but in general you cannot guarantee their existence:

http://stackoverflow.com/questions/5090737/datatypes-used-in-c

**Comment by vext01** [comment]
(I would like to squash the two type changes into one commit)

**Comment by ltratt** [comment]
Ah, so we don't define u_int64_t ourselves?

**Comment by vext01** [comment]
No, it's defined in the system headers on some systems.

**Comment by vext01** [comment]
(C is a mess)

**Comment by ltratt** [comment]
I'm with you! OK, let's squash then I can merge.

**Comment by vext01** [comment]
Splat.

**Pull request merged**
