### PR TITLE
Misc bits

### LINKED ISSUE #335: Spaces in VM names causes a crash.
```
tfransham: 11:41 AM: flag, key = line.strip().split(" ")  breaking on spaces in vm names
```

### PR DESCRIPTION
**Pull request by vext01**
Tom, these are some minor bits and bobs that you found last week.

Looks good? Doesn't need to be squashed.

Fixes #335

### CODE REVIEW

**Comment by fsfod** [comment]
What about spaces in vm names?

**Comment by vext01** [comment]
I was going to fix that in a separate PR, but I can lump it in here if you prefer?

**Comment by fsfod** [comment]
just do it in this one

**Comment by vext01** [comment]
Try this.

**Comment by fsfod** [comment]
You could just replace them with an underscore maybe?

**Comment by vext01** [comment]
I'd rather just flag it as an error.

**Comment by fsfod** [comment]
@vext01 did you want to rebase this on master instead of me doing it in the merge?

**Comment by vext01** [comment]
Yep, one moment.

**Comment by vext01** [comment]
Rebased. Merge when ready.

**Pull request merged**
