### PR TITLE
Ignore desmg lines relating to bringing the network down/up on Linux.

### PR DESCRIPTION
**Pull request by vext01**
Tested with real reboots.

OK?

### CODE REVIEW

**Comment by snim2** [comment]
I can't see where that new method is called...

**Comment by vext01** [comment]
```
    def check_dmesg_for_changes(self):                                          
        new_dmesg = self._collect_dmesg_lines()                                 
        patterns = self.get_allowed_dmesg_patterns()                            
```

I'm overriding a more generic implementation.

**Comment by snim2** [comment]
OK, I see it! This seems OK to me. Do you want @ltratt to review also?

**Comment by vext01** [comment]
This one is pretty trivial, so we can go ahead I think. The other one, I would like his input on.

**Pull request merged**
