### PR TITLE
Revise ruby runner to call JRuby libkruntime wrapper.

### LINKED ISSUE #95: Ruby runner uses wrong timer if run under JRuby.
This was originally report by @cfbolz here (https://github.com/softdevteam/warmup_experiment/issues/55):

The Ruby runner contains this code:

```
if /linux/ =~ RUBY_PLATFORM
    MONOTONIC_CLOCK = Process::CLOCK_MONOTONIC_RAW
else
    MONOTONIC_CLOCK = Process::CLOCK_MONOTONIC
end
```

however, on JRuby ``RUBY_PLATFORM`` is "java", thus the wrong timer is used. Here is a discussion how to fix this: https://www.ruby-forum.com/topic/150942

### PR DESCRIPTION
**Pull request by vext01**
See also https://github.com/softdevteam/warmup_experiment/pull/56

OK?

Fixes #95

### CODE REVIEW

**Comment by cfbolz** [comment]
Hm, I wonder whether we should still support MRI in the runner (by having a check for ``RUBY_PLATFORM != "JRuby"`` or so).

**Comment by vext01** [comment]
If you know a way to detect JRuby, then by all means :)

**Comment by eregon** [comment]
I am implementing `Process.clock_gettime(Process::CLOCK_MONOTONIC_RAW)` in JRuby+Truffle on Linux, so this workaround should not be needed then, unless you prefer to use your native library.

**Comment by vext01** [comment]
As long as it results in a call to `clock_gettime(CLOCK_MONOTONIC_RAW, ...)` on linux.

**Comment by eregon** [comment]
yes it does as of https://github.com/jruby/jruby/commit/4221e4d147a1818f42d35f5ba8426647f8408ca2,
although it might have some overhead as there is some FFI cost (also happens with the other approach).

**Comment by cfbolz** [comment]
you can detect JRuby like this, no?: ``RUBY_PLATFORM``

**Comment by vext01** [comment]
@eregon We are currently stuck on an older version of JRuby/Truffle as we were having issues building a newer one (although I don't fully remember the details now). We would only be able to use such a fix if we could get a newer JRuby/Truffle working.

**Comment by eregon** [comment]
@vext01 No problem, use what works for you!
(if it was a missing maven snapshot it should be fixed)

**Comment by vext01** [comment]
This should do the trick. OK?

**Comment by cfbolz** [comment]
Ok, great!

**Pull request merged**
