### PR TITLE
Fix tests which are broken on a uniprocessor machine.

### PR DESCRIPTION
**Pull request by vext01**
These failures were exposed by development in a Debian VM.

Tickless kernels are irrelevant on a uniprocessor machine and this
caused some tests which are expected to fail to not.

Also add a test which checks that a kernel without tickless mode works
if the machine has only one CPU.

This is unrelated to #396 -- just I found these failures while doing that.

### CODE REVIEW

**Comment by ltratt** [comment]
What does `platform.num_cpus = 2` mean/do? I initially thought it was an assertion of sorts, but then realised it was an assignment, and I'm not sure how you assign a number of CPUs?

**Comment by vext01** [comment]
It's tricking the platform abstractions into thinking that there are two CPUs. This is needed to prevent the platform being OK with a non-tickless kernel on account of the test host being uni-processor.

Think of it as a poor-man's mock.

**Comment by ltratt** [comment]
OK, got it!

**Comment by vext01** [comment]
> This is needed to prevent the platform being OK with a non-tickless kernel on account of the test host being uni-processor.

I should elaborate. A "fully tickless" kernel needs one "non-tickless" CPU to manage the other tickless cores. If you only have one CPU, then you can't have any tickless cores and Krun is fine with that.

In reality I doubt we will ever see a bare-metal uniprocessor machine ever again anyway! :P

**Pull request merged**
