### PR TITLE
Interactive analysis mode.

### PR DESCRIPTION
**Pull request by vext01**
This is a branch that I started last sprint. It replaces the HTML reports with an interactive mode. I don't think the HTML mode is useful any more, so let's merge it in. I've recently tidied up all the dead code and improved the UI a bit.

Since this is pretty much a rewrite of `mk_graphs.py`, I am going to recommend we squash the whole lot.

### CODE REVIEW

**Comment by ltratt** [comment]
This seems a huge amount of commits for a relatively small amount of code. Can some pointless commits (e.g. the merge) be squashed?

**Comment by vext01** [comment]
Yes, as mentioned in the original PR description, I would like to squash this. Since we are in agreement, I've gone ahead and done that.

**Comment by ltratt** [comment]
Sorry, I completely missed that bit -- mea culpa!

**Comment by ltratt** [comment]
Looks good -- merged.

**Comment by vext01** [comment]
Thanks

**Pull request merged**
