### PR TITLE
Run benchmarks at highest priority. 

### PR DESCRIPTION
**Pull request by snim2**
Resolves Issue #55.

### CODE REVIEW

**Comment by vext01** [comment]
Looks good.

Initially I was worried that we might end up nicing taskset, however `platform.bench_cmdline_adjust()` *prepends* arguments, so I think we are OK. Do you agree?

May I suggest a constant for the nice value used?

**Comment by ltratt** [comment]
Given that `nice` values won't change, I'm not sure a constant is that useful.

**Comment by vext01** [comment]
I tend to define constants instead of magic numbers. Up to you Sarah.

**Comment by snim2** [comment]
I agree a constant is not strictly necessary, but it is more consistent with the original code. Will rebase...

**Comment by vext01** [comment]
LGTM

**Pull request merged**
