### PR TITLE
Fix pypy instr parser

### PR DESCRIPTION
**Pull request by vext01**
OK?

### CODE REVIEW

**Comment by vext01** [comment]
It asserts some things that shouldn't happen.

**Comment by ltratt** [comment]
Ah, hang on, are you saying that the problem before was that an `assert` fired when it shouldn't have?

**Comment by vext01** [comment]
Yep.

I had assumed that no events were emitted after the end of the last iteration, but ofcourse the iterations ruunner still has some work to do, like emit results, during which time VM event can occur.

The assertion was: "ensure that the only node left in the event tree is a jit-summary node" <-- to strong.

And is now: "Ensure there exists a JIT summary node in the remaining VM events"

**Comment by ltratt** [comment]
OK, that makes sense. I suggest you squash, we wait for the tests to complete, then I'll merge.

**Comment by vext01** [comment]
splat

**Comment by vext01** [comment]
splat

**Comment by vext01** [comment]
Don't forget this btw :)

**Comment by vext01** [comment]
Sorry. Posted my comment, then the "ltratt merged" thing appeared. Ignore.

**Pull request merged**
