### PR TITLE
More oracle vm fixes

### PR DESCRIPTION
**Pull request by vext01**
Invoke Graal using mx.

Accompanies https://github.com/softdevteam/warmup_experiment/pull/127

OK?

### CODE REVIEW

**Comment by vext01** [comment]
Need to sync with master, one moment.

**Comment by vext01** [comment]
synced.

**Comment by snim2** [comment]
Looks fine to me....

**Comment by vext01** [comment]
squash.

**Comment by vext01** [comment]
There's a corresponding change in the warmup experiment here btw:
https://github.com/softdevteam/warmup_experiment/pull/127

**Pull request merged**
