### PR TITLE
Kill log timestamp

### LINKED ISSUE #344: Remove timestamp from log file name.
There's a racy timestamp on the log file name created by Krun. Since the other files we create are not timestamped, I suggest we just kill the timestamp, thus making the code simple.

### PR DESCRIPTION
**Pull request by vext01**
Fixes #344 

I like this one, as it removes more code than it adds :)

Assigning Sarah, as it's her code I'm killing :smiling_imp: 

OK?

### CODE REVIEW

**Comment by snim2** [comment]
*sniff* and I worked so hard on that code! 
Do we want to check that the user does not have an extant `.log` file before Krun starts?

**Comment by vext01** [comment]
It's probably not a big deal, but we could if you like.

**Comment by snim2** [comment]
Well, do we do the same for the env logs and so on, or do we just check the manifest?

**Comment by vext01** [comment]
I think you are right. I'll do that tomorrow now :)

**Comment by vext01** [comment]
@snim2 here's the check. OK to squash?

**Comment by snim2** [comment]
Looks good to me, please squash away!

**Comment by vext01** [comment]
splat

**Comment by snim2** [comment]
Thanks

**Pull request merged**
