### PR TITLE
Sanitise audit objects. 

### LINKED ISSUE #103: Improve rudimentary platform check
When using resume-model, Krun performs a rudimentary checks to determine whether the benchmark is being resumed on the same machine that it was started on. Currently, this check only checks that the `uname` of the two machines is identical.

This test should differ between platforms, and it would make sense to refactor it into the classes in `platform.py`. This may happen as part of #75 

For Linux, we could use a strong check such as `blkid`, which returns a unique ID of the root file system. I guess someone could have installed more RAM between resumes, so this doesn't catch every case, but anyhow @ltratt felt this was overkill and suggested we use `hostname`, which is available on most (all?) Unix like platforms.

A more detailed fix would check every value in the audit dictionary. However, `platform.audit()` returns a `str`, but the audit in the JSON file is a `unicode`. On my machine I have packages with names that contain acutes and other accents, and a `==` between "this" platform and the previous one always returned `False`. The Internet contains a wide variety of solutions to this problem, and I didn't get any of them to quite work: hence the current hack.

### PR DESCRIPTION
**Pull request by snim2**
Store all strings as unicode. 
Remove complex tests for equality.

Fixes #103 
(resolves rather than fixes!)

### CODE REVIEW

**Comment by vext01** [comment]
LGTM

**Comment by vext01** [comment]
But we need to rebase.

**Comment by snim2** [comment]
Rebased.

**Comment by snim2** [comment]
rebased.

**Pull request merged**
