### PR TITLE
Fix Config.should_skip().

### PR DESCRIPTION
**Pull request by vext01**
If a star appeared in SKIP in the config file, it screws up
should_skip() for later elemets in SKIP.

Did not affect our full experiment by pure chance.

Threw in some more test cases for good measure.

Please don't merge just yet. Want to double check something.

### CODE REVIEW

**Comment by snim2** [comment]
This looks nice, especially the randomised test.

**Comment by vext01** [comment]
OK, I just checked that the scheduler queue is the right length for the warmup experiment. It is :)

9 vms * 6 benchmarks - 6 (skip all CPython benchs) -3 (crashing or slow) = 45. And we have:

```
[2016-01-14 13:28:49 INFO] Benchmarking started.
Logging to warmup_20160114_132849.log
[2016-01-14 13:28:50 INFO] 90 jobs left in scheduler queue
[2016-01-14 13:28:50 INFO] Estimated completion     : ????-??-?? ??:??:?? (?:??:?? from now)
[2016-01-14 13:28:50 INFO] Jobs until ETA known: 45
```

The 90 is 45 * 2 executions. Looks good to me.

Go ahead and merge if you are happy.

**Comment by snim2** [comment]
I'm happy to merge, do you want to add an automated test for the length of the schedule or do you think the ones we have in `test_scheduler` are enough?

**Comment by vext01** [comment]
Good idea. Hold on.

**Comment by vext01** [comment]
Sorry for the delay, try this.

**Comment by snim2** [comment]
Looks good. Do you want to squash?

**Comment by vext01** [comment]
Splat.

**Comment by vext01** [comment]
Thanks muchly

**Pull request merged**
