### PR TITLE
Yet more type stability

### LINKED ISSUE #383: Python Iteration Runner Broken
```
[iterations_runner.py] iteration 1/1
Traceback (most recent call last):
  File "/home/kruninit/warmup_experiment/krun/iterations_runners/iterations_runner.py", line 166, in <module>
    sys.stdout.write("%s\n" % json.dumps(js))
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: array('L', [96252L]) is not JSON serializable
```

The typed array cannot be encoded to JSON it seems.

### PR DESCRIPTION
**Pull request by vext01**
Some more type stability stuff, and a fix for the Python runner.

Tested on bencher7.

Fixes #383

### CODE REVIEW

**Comment by fsfod** [comment]
would -0.0  be a better value?

**Comment by vext01** [comment]
Maybe, but which language are we talking about? Lua? Why -0.0?

**Comment by ltratt** [comment]
I'm inclined to agree with Tom: `0.0` *could* be optimised to `0` easily enough; but `-0.0` is very hard to optimise that way (not impossible, but so hard I can't imagine anyone will ever bother trying).

**Comment by fsfod** [comment]
I was thinking Lua idk if the parser might simplify 0.0 to a integer zero i also realised that LuaJIT has dual num mode. The types would be only switching one array slot at a time though not whatever craziness javascript does.

**Comment by vext01** [comment]
Try this. I just need to test it quickly.

**Comment by ltratt** [comment]
Looks good to me. Assuming it works, please squash, and I'll then merge.

**Comment by vext01** [comment]
Works fine, squash coming.

**Comment by ltratt** [comment]
Did you squash?

**Comment by vext01** [comment]
I did. My splat message seems to have gone missing.

Please merge if you are happy.

**Pull request merged**
