### PR TITLE
Add basic travis config

### PR DESCRIPTION
**Pull request by snim2**
There are some tests in `krun/tests/` which can be run with py.test, and some of the work for Issue #41 (such as appending to a JSON file) are testable. 

This PR adds a travis config to run these tests automatically.

### CODE REVIEW

**Comment by snim2** [comment]
We need to turn travis on in the repo, and also the travis account needs to turn the repo on (if that makes sense). I'm not sure whether this github account already has a travis account?

**Comment by vext01** [comment]
Are you happy to look into that?

**Comment by snim2** [comment]
I can do all that, but I think I need the password to this GH account, otherwise everything will end up being owned by snim2.

**Comment by vext01** [comment]
I don't think there is an account for the team. Just admins for the team?

**Comment by snim2** [comment]
Hmm. OK, well I'll have a go, and if we aren't happy with the set up we can always change it later.

**Comment by vext01** [comment]
Good luck!

**Comment by snim2** [comment]
OK, this seems to be fine: https://travis-ci.org/softdevteam/krun

**Comment by vext01** [comment]
Nice! Well done.

**Pull request merged**
