### PR TITLE
Add a "VM definition" for native code.

### PR DESCRIPTION
**Pull request by vext01**
Add a "VM definition" for native code benchmarks, e.g. C.

Required a little boilerplate hacking and fix a bad abstract signature while we are here.

OK?

### CODE REVIEW

**Comment by snim2** [comment]
Looks OK to me. 

This isn't in this PR, but reading through the surrounding code I was initially confused by `NotImplementedError("abstract")`, which I would usually write as something like `NotImplementedError("method must be overridden in subclass")` (if I've understood this correctly).

**Comment by vext01** [comment]
It's an idiom I've picked up from PyPy.

In a sense the message is moot, as the line should never be executed ;)

I've just done some searching on the net, and apparently the "official" way is to use the `abc` module and `@abstractmethod`. Shall we try it?

**Comment by snim2** [comment]
That sounds like a good idea to me. I see the relevant PEP (3119) was accepted in 2007, so I would guess that this exists in the PyPy stdlib too.

**Comment by vext01** [comment]
OK, let's merge this, then I'll make a new PR doing the abstract stuff.

**Comment by vext01** [comment]
thanks!

**Pull request merged**
