### PR TITLE
Remove tracing events from PYPYLOG.

### PR DESCRIPTION
**Pull request by vext01**
I think this will fix our issues with the PYPYLOG parser.

I will run a reduced experiment on bencher2 overnight.

Until then, looks OK?

Also maybe of interest to @cfbolz

### CODE REVIEW

**Comment by vext01** [comment]
My test run on bencher2 completed without issue and the logged data looks OK. Shall we push ahead?

**Comment by ltratt** [comment]
Squash and I can merge?

**Comment by vext01** [comment]
Splat

**Comment by ltratt** [comment]
Will merge once tests have run.

**Pull request merged**
