### PR TITLE
Resilience

### PR DESCRIPTION
**Pull request by vext01**
Make krun more resilient in the face of crashing benchmarks.

I'm happy with the commit structure.

OK?

### CODE REVIEW

**Comment by vext01** [comment]
Squashed last two commits, as requested on irc.

**Comment by vext01** [comment]
Ready.

**Comment by vext01** [comment]
Not ready, we both posted an once.

**Comment by vext01** [comment]
WRT eval. We can certainly parse the output, although: a) i don't think security matters much for a benchmark runner, and b)  bear in mind the config file reading is pretty much a big eval also.

I've wanted to re-write the way configuration works for some time, but it's not a small task and too many other things are higher priority.

**Comment by cfbolz** [comment]
If it's literally a list of floats, just use ``json.loads(stdout)``

**Comment by ltratt** [comment]
It's my fault for not spotting the `eval` earlier, but it has to be removed.

**Comment by vext01** [comment]
What about the config file?
https://github.com/softdevteam/krun/blob/master/krun/util.py#L31

Let's at-least raise an issue for this and I can look at it after the pyhyp deadline. Juggling too many things at once.

**Comment by ltratt** [comment]
The config file is fine as an `eval`, because the user should know what they're doing (and, if they don't, bad luck) -- and the flexibility can be actively useful. The problem with parsing random output from a program is that it might accidentally produce incorrect output which is `eval`able and changes the program state.

**Comment by vext01** [comment]
Try this.

**Comment by ltratt** [comment]
I think the last 3 commits should be squashed (it doesn't make sense to have individual commits which can't work on their own). Then I think we're probably ready to merge (although maybe it's worth removing the "eval syntax error" commit entirely?).

**Comment by vext01** [comment]
I was unable to cleanly pull out the syntaxerror exception commit, as future commits depend upon it.

Squashed the JSON related commits into one, but since the indent fixes are on lines untouched by the json fix, I think it should remain separate. Would you agree?

**Comment by ltratt** [comment]
Since you were editing that file anyway, I think touching up non-critical indents might as well be folded in.

**Comment by vext01** [comment]
OK squashed. Note that I have gotten in trouble in the past (albeit outside of softdev) for mushing style changes with functional changes. One to bear in mind.

OK to merge?

**Comment by ltratt** [comment]
Minor whitespace fixes of a few lines are pretty common IME, and I don't see a problem in bundling them up. Of course, there's an element of judgement in this.

Anyway, this looks ready for merging. Good stuff!

**Pull request merged**
