### PR TITLE
Expose clock_gettime_monotonic in JNI.

### PR DESCRIPTION
**Pull request by snim2**
Related to warmup Issue 181

### CODE REVIEW

**Comment by vext01** [comment]
You need a JNIEXPORT function in libkruntime.c and libkruntime.h too.

**Comment by vext01** [comment]
Looks good. Have you tested it?

**Comment by snim2** [comment]
This now builds, and produces data:

```python
>>> from warmup.krun_results import read_krun_results_file
>>> data = read_krun_results_file("startup_results.json.bz2")
>>> data["wallclock_times"]["binarytrees:Hotspot:default-java"]
[[4562108.930327, 4562108.95932]]
>>> data["wallclock_times"]["binarytrees:Graal:default-java"]
[[4562116.44605, 4562116.697726]]
>>> 
```

**Comment by vext01** [comment]
I think the interval is the second value minus the first.

We would need to post-process the startup results file.

**Comment by snim2** [comment]
OK, I'll add this to the relevant issue in warmup.

**Comment by vext01** [comment]
Notice how we have `ITERATIONS_ALL_VMS = 1` in the config file, but 2 elements of results. This is because the existing results file is re-used for a different purpose. The idea was to not have to change krun too much.

**Comment by snim2** [comment]
Am I OK to squash this?

**Comment by vext01** [comment]
Go ahead.

**Comment by snim2** [comment]
@ltratt ?

**Comment by ltratt** [comment]
I'm not a useful reviewer on this, so I've taken myself off.

**Comment by snim2** [comment]
All squished.

**Pull request merged**
