### PR TITLE
Tickless

### LINKED ISSUE #60: Tickless operation on linux
As raised by ltratt, we may need to use tickless mode on linux:
http://lwn.net/Articles/549580/

Our debian 8 systems currently run idle tickless mode:
```
vext01@bencher3:~$ cat /boot/config-`uname -r` | grep HZ
CONFIG_NO_HZ_COMMON=y
# CONFIG_HZ_PERIODIC is not set
CONFIG_NO_HZ_IDLE=y
# CONFIG_NO_HZ_FULL is not set <--------------------- this would need to be on!
# CONFIG_NO_HZ is not set
CONFIG_RCU_FAST_NO_HZ=y
# CONFIG_HZ_100 is not set
CONFIG_HZ_250=y
# CONFIG_HZ_300 is not set
# CONFIG_HZ_1000 is not set
CONFIG_HZ=250
CONFIG_MACHZ_WDT=m
```

To fix this, we would need to build a custom kernel. Another impractical step unfortunately.

Opening bug for discussion. @ltratt @snim2 @cfbolz

### PR DESCRIPTION
**Pull request by vext01**
Check for tickless Linux kernel.

Tested before and after build+install of a tickless kernel.

I thought about adding instructions on how to build the tickless kernel, but I'm not sure where to put them at this stage.

Fixes #60.

OK?

### CODE REVIEW

**Comment by snim2** [comment]
OK, you can ignore the failing travis build as we remove Python 2.6 in PR #74 

The documentation should be added to `examples/README.md` where updating grub is described. Since PR #74 is so big, it might be sensible to make that documentation update a separate PR. Can you add that to Issue #57 so we don't forget?

**Comment by vext01** [comment]
Add docs. OK to merge?

**Comment by vext01** [comment]
(it was onlya small change, so I just put it in this PR)

**Comment by snim2** [comment]
OK, but then you can't merge #74 until I have done a `pull --rebase` and merged your changes in

**Pull request merged**
