### PR TITLE
Summarise progress from manifest files

### PR DESCRIPTION
**Pull request by snim2**
This PR adds a script written by @vext01 to source control. The script reads a manifest file and prints a summary of the progress through the current experiment, e.g.:

```bash
$ ./scripts/progress.awk warmup.manifest 
C=349  O=191  E=0   64.6296%
```

### CODE REVIEW

**Comment by ltratt** [comment]
Does this work with the updated manifest w/temperatures in it?

**Comment by snim2** [comment]
I don't have one to try, but it only counts the relevant lines, so should do

**Comment by ltratt** [comment]
Good point. Then I think we can take this in as-is.

**Comment by vext01** [comment]
It ignores all lines preceeding the keys line:
```
/^keys/         {keys=1}
```

**Pull request merged**
